# Generated by Django 3.0.4 on 2020-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200324_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='MAKALEYE FOTOGRAF YUKLEYIN'),
        ),
    ]
